/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ParticipantDto } from '../../models/participant-dto';

export interface LaufbewerbeIdTeilnehmerGet$Params {
  id: number;
}

export function laufbewerbeIdTeilnehmerGet(http: HttpClient, rootUrl: string, params: LaufbewerbeIdTeilnehmerGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ParticipantDto>> {
  const rb = new RequestBuilder(rootUrl, laufbewerbeIdTeilnehmerGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ParticipantDto>;
    })
  );
}

laufbewerbeIdTeilnehmerGet.PATH = '/laufbewerbe/{id}/teilnehmer';
