/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EvalReqDto } from '../../models/eval-req-dto';
import { EvaluationDto } from '../../models/evaluation-dto';

export interface LaufbewerbeAuswertungPost$Params {
      body: EvalReqDto
}

export function laufbewerbeAuswertungPost(http: HttpClient, rootUrl: string, params: LaufbewerbeAuswertungPost$Params, context?: HttpContext): Observable<StrictHttpResponse<EvaluationDto>> {
  const rb = new RequestBuilder(rootUrl, laufbewerbeAuswertungPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EvaluationDto>;
    })
  );
}

laufbewerbeAuswertungPost.PATH = '/laufbewerbe/auswertung';
