/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ValidationResult } from '../../models/validation-result';

export interface ValidateBracelet$Params {
  data: string;
}

export function validateBracelet(http: HttpClient, rootUrl: string, params: ValidateBracelet$Params, context?: HttpContext): Observable<StrictHttpResponse<ValidationResult>> {
  const rb = new RequestBuilder(rootUrl, validateBracelet.PATH, 'get');
  if (params) {
    rb.path('data', params.data, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ValidationResult>;
    })
  );
}

validateBracelet.PATH = '/bracelets/validate/{data}';
