/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CompetitionDto } from '../../models/competition-dto';

export interface GetCompetitions$Params {
  name?: string;
  categoryId?: number;
}

export function getCompetitions(http: HttpClient, rootUrl: string, params?: GetCompetitions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CompetitionDto>>> {
  const rb = new RequestBuilder(rootUrl, getCompetitions.PATH, 'get');
  if (params) {
    rb.query('name', params.name, {});
    rb.query('categoryId', params.categoryId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CompetitionDto>>;
    })
  );
}

getCompetitions.PATH = '/laufbewerbe';
