/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BraceletDto } from '../models/bracelet-dto';
export interface OrderDetailDto {
  customerName: string;
  id: number;
  numberOfBracelets: number;
  orderDate: string;
  orderItems: Array<BraceletDto>;
  totalCost: number;
}
