/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Exception } from '../models/exception';
import { MethodBase } from '../models/method-base';
export type AggregateException = {
'innerExceptions'?: Array<Exception> | null;
'message'?: string | null;
'targetSite'?: MethodBase | null;
'data'?: {
} | null;
'innerException'?: Exception;
'helpLink'?: string | null;
'source'?: string | null;
'hResult'?: number;
'stackTrace'?: string | null;
};

