/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryDto } from './models/category-dto';
export type { CompetitionDto } from './models/competition-dto';
export type { CompetitionReqDto } from './models/competition-req-dto';
export type { ComputeReqDto } from './models/compute-req-dto';
export type { EvaluationDto } from './models/evaluation-dto';
export type { ParticipantDto } from './models/participant-dto';
export type { SplitEvaluationDto } from './models/split-evaluation-dto';
