/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { VerifyPinNamePost$Params as VerifyPinNamePost$Params } from './fn/web-api/verify-pin-name-post';
export { verifyPinNamePost as verifyPinNamePost } from './fn/web-api/verify-pin-name-post';
export type { WishlistNameItemsPost$Params as WishlistNameItemsPost$Params } from './fn/web-api/wishlist-name-items-post';
export { wishlistNameItemsPost as wishlistNameItemsPost } from './fn/web-api/wishlist-name-items-post';
export type { WishlistNameItemsItemIdMarkAsBoughtPost$Params as WishlistNameItemsItemIdMarkAsBoughtPost$Params } from './fn/web-api/wishlist-name-items-item-id-mark-as-bought-post';
export { wishlistNameItemsItemIdMarkAsBoughtPost as wishlistNameItemsItemIdMarkAsBoughtPost } from './fn/web-api/wishlist-name-items-item-id-mark-as-bought-post';
export type { WishlistNameItemsItemIdDelete$Params as WishlistNameItemsItemIdDelete$Params } from './fn/web-api/wishlist-name-items-item-id-delete';
export { wishlistNameItemsItemIdDelete as wishlistNameItemsItemIdDelete } from './fn/web-api/wishlist-name-items-item-id-delete';
export type { WishlistNameItemsAddPost$Params as WishlistNameItemsAddPost$Params } from './fn/web-api/wishlist-name-items-add-post';
export { wishlistNameItemsAddPost as wishlistNameItemsAddPost } from './fn/web-api/wishlist-name-items-add-post';
export type { GiftCategoriesGet$Params as GiftCategoriesGet$Params } from './fn/web-api/gift-categories-get';
export { giftCategoriesGet as giftCategoriesGet } from './fn/web-api/gift-categories-get';
