/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimeEntry } from '../models/time-entry';
export interface Employee {
  employeeId?: string;
  employeeName?: string;
  id?: number;
  timeEntries?: Array<TimeEntry>;
}
