/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CompetitionReqDto {
  categoryId: number;
  date: string;
  length: number;
  name: string;
  place: string;
}
