/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';

export interface GetTimeEntries$Params {
  employeeId?: number;
  projectId?: number;
}

export function getTimeEntries(http: HttpClient, rootUrl: string, params?: GetTimeEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TimeEntry>>> {
  const rb = new RequestBuilder(rootUrl, getTimeEntries.PATH, 'get');
  if (params) {
    rb.query('employeeId', params.employeeId, {});
    rb.query('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TimeEntry>>;
    })
  );
}

getTimeEntries.PATH = '/timeentries';
