/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry2 } from '../../models/time-entry-2';

export interface GetTimeEntry$Params {
  id: number;
}

export function getTimeEntry(http: HttpClient, rootUrl: string, params: GetTimeEntry$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntry2>> {
  const rb = new RequestBuilder(rootUrl, getTimeEntry.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntry2>;
    })
  );
}

getTimeEntry.PATH = '/timeentries/{id}';
