/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TravelListItemDto } from '../../models/travel-list-item-dto';

export interface GetTravels$Params {
}

export function getTravels(http: HttpClient, rootUrl: string, params?: GetTravels$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TravelListItemDto>>> {
  const rb = new RequestBuilder(rootUrl, getTravels.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TravelListItemDto>>;
    })
  );
}

getTravels.PATH = '/travels';
