/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetCategories$Params as GetCategories$Params } from './fn/laufbewerbe-endpoints/get-categories';
export { getCategories as getCategories } from './fn/laufbewerbe-endpoints/get-categories';
export type { GetCompetitions$Params as GetCompetitions$Params } from './fn/laufbewerbe-endpoints/get-competitions';
export { getCompetitions as getCompetitions } from './fn/laufbewerbe-endpoints/get-competitions';
export type { UpdateCompetition$Params as UpdateCompetition$Params } from './fn/laufbewerbe-endpoints/update-competition';
export { updateCompetition as updateCompetition } from './fn/laufbewerbe-endpoints/update-competition';
export type { CreateCompetition$Params as CreateCompetition$Params } from './fn/laufbewerbe-endpoints/create-competition';
export { createCompetition as createCompetition } from './fn/laufbewerbe-endpoints/create-competition';
export type { GetCompetitionById$Params as GetCompetitionById$Params } from './fn/laufbewerbe-endpoints/get-competition-by-id';
export { getCompetitionById as getCompetitionById } from './fn/laufbewerbe-endpoints/get-competition-by-id';
export type { DeleteCompetition$Params as DeleteCompetition$Params } from './fn/laufbewerbe-endpoints/delete-competition';
export { deleteCompetition as deleteCompetition } from './fn/laufbewerbe-endpoints/delete-competition';
export type { LaufbewerbeIdTeilnehmerGet$Params as LaufbewerbeIdTeilnehmerGet$Params } from './fn/auswertung-endpoints/laufbewerbe-id-teilnehmer-get';
export { laufbewerbeIdTeilnehmerGet as laufbewerbeIdTeilnehmerGet } from './fn/auswertung-endpoints/laufbewerbe-id-teilnehmer-get';
export type { LaufbewerbeAuswertungPost$Params as LaufbewerbeAuswertungPost$Params } from './fn/auswertung-endpoints/laufbewerbe-auswertung-post';
export { laufbewerbeAuswertungPost as laufbewerbeAuswertungPost } from './fn/auswertung-endpoints/laufbewerbe-auswertung-post';
