/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryDto } from './models/category-dto';
export type { CompetitionDto } from './models/competition-dto';
export type { CompetitionReqDto } from './models/competition-req-dto';
export type { EvalReqDto } from './models/eval-req-dto';
export type { EvaluationDto } from './models/evaluation-dto';
export type { ParticipantDto } from './models/participant-dto';
export type { SplitDto } from './models/split-dto';
