/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoItem } from '../../models/todo-item';

export interface GetAllTodoItems$Params {
}

export function getAllTodoItems(http: HttpClient, rootUrl: string, params?: GetAllTodoItems$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TodoItem>>> {
  const rb = new RequestBuilder(rootUrl, getAllTodoItems.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TodoItem>>;
    })
  );
}

getAllTodoItems.PATH = '/items';
