/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryDto } from '../models/category-dto';
export interface CompetitionDto {
  category: CategoryDto;
  date: string;
  id: number;
  length: number;
  name: string;
  place: string;
}
