/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SplitDto {
  avgVelocity: number;
  goalAchieved: boolean;
  km: number;
  length: number;
  time: number;
}
