/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SplitDto {
  avgVelocity: string;
  goalAchieved: boolean;
  km: number;
  length: number;
  time: string;
}
