/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { GetEmployees$Params } from './fn/web-api/get-employees';
export { getEmployees } from './fn/web-api/get-employees';
export type { GetProjects$Params } from './fn/web-api/get-projects';
export { getProjects } from './fn/web-api/get-projects';
export type { GetTimeEntries$Params } from './fn/web-api/get-time-entries';
export { getTimeEntries } from './fn/web-api/get-time-entries';
export type { GetTimeEntry$Params } from './fn/web-api/get-time-entry';
export { getTimeEntry } from './fn/web-api/get-time-entry';
export type { UpdateTimeEntry$Params } from './fn/web-api/update-time-entry';
export { updateTimeEntry } from './fn/web-api/update-time-entry';
export type { TimeentriesIdDelete$Params } from './fn/web-api/timeentries-id-delete';
export { timeentriesIdDelete } from './fn/web-api/timeentries-id-delete';
