/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthReq } from '../../models/auth-req';
import { VerifyPinResp } from '../../models/verify-pin-resp';

export interface VerifyPinNamePost$Params {
  name: string;
      body: AuthReq
}

export function verifyPinNamePost(http: HttpClient, rootUrl: string, params: VerifyPinNamePost$Params, context?: HttpContext): Observable<StrictHttpResponse<VerifyPinResp>> {
  const rb = new RequestBuilder(rootUrl, verifyPinNamePost.PATH, 'post');
  if (params) {
    rb.path('name', params.name, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<VerifyPinResp>;
    })
  );
}

verifyPinNamePost.PATH = '/verify-pin/{name}';
